install:
    crash_reporting:
        enabled: true
        type: "crashpad"
    game-settings:
        accountId: 3136566109439360
        modified: false
        timestamp: 0
    gameflow-patcher-lock: null
    gameflow-process-info: null
    gameflow-spectate-reconnect-info: null
    globals:
        locale: "vi_VN"
        region: "VN2"
    lcu-settings:
        accountId: 3136566109439360
        modified: false
        timestamp: 0
    patcher:
        client_migrated: true
        client_patcher_available: true
        game_migrated: true
        game_patcher_available: true
        locales:
        - "vi_VN"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    perks-settings:
        accountId: 3136566109439360
        modified: false
        timestamp: 0
    riotclient-upgrade:
        seq-success-count: 236
        success-count: 236
    rso-auth:
        install-identifier: "c19747ee874926408835c976728845a4"
